### PR TITLE
student code from cs169 sp19 team 4

### PR DESCRIPTION
**Pull request by Chenlibo**
1. added vetting statuses. staff now can add vetting comments to each app. App listing page can show only the apps in vetting status. Repo URL is optional when creating a new app in vetting status
2. added app counts on `index` page
3. added "email to organizations" functionality. 
4. added support for rich text editing and display
5. added pagination
6. enhanced search bar
7. Miscellaneous: 
   - add a hyperlink to org name and user name, 
   - `back` redirect to app's `show` page instead of the `index` page, 
   - moved `back` and `edit` buttons to the top right
   - added app status in app's `show` page
8. added documentation
9. added `features` to `app` and `engagement`

### CODE REVIEW

**Comment by an-ju** [comment]
Please update the README about the new features.

**Comment by an-ju** [comment]
I had the problem with OpenSSL when setting it up locally.  If this is a common problem, please refer to a good solution to it in your README.

**Comment by Chenlibo** [comment]
> I had the problem with OpenSSL when setting it up locally. If this is a common problem, please refer to a good solution to it in your README.

one of our team members had an openssl issue, but I forget how we resolved it

**Comment by an-ju** [comment]
> > I had the problem with OpenSSL when setting it up locally. If this is a common problem, please refer to a good solution to it in your README.
> 
> one of our team members had an openssl issue, but I forget how we resolved it

OK...  There're still problems with setting the app up.  Please create a Tracker story to record the problem.  Please update the README and let me know when the updates are done.

**Comment by Chenlibo** [comment]
> > > I had the problem with OpenSSL when setting it up locally. If this is a common problem, please refer to a good solution to it in your README.
> > 
> > 
> > one of our team members had an openssl issue, but I forget how we resolved it
> 
> OK... There're still problems with setting the app up. Please create a Tracker story to record the problem. Please update the README and let me know when the updates are done.

wait, what exactly are the problems?

**Comment by an-ju** [comment]
> > > > I had the problem with OpenSSL when setting it up locally. If this is a common problem, please refer to a good solution to it in your README.
> > > 
> > > 
> > > one of our team members had an openssl issue, but I forget how we resolved it
> > 
> > 
> > OK... There're still problems with setting the app up. Please create a Tracker story to record the problem. Please update the README and let me know when the updates are done.
> 
> wait, what exactly are the problems?

I changed my ruby version to a version that has OpenSSL (2.4.1 eventually).  But then I'm having troubles with `rake db:setup`.   I don't have a solution for that error yet.

**Comment by Chenlibo** [comment]
> > > > > I had the problem with OpenSSL when setting it up locally. If this is a common problem, please refer to a good solution to it in your README.
> > > > 
> > > > 
> > > > one of our team members had an openssl issue, but I forget how we resolved it
> > > 
> > > 
> > > OK... There're still problems with setting the app up. Please create a Tracker story to record the problem. Please update the README and let me know when the updates are done.
> > 
> > 
> > wait, what exactly are the problems?
> 
> I changed my ruby version to a version that has OpenSSL (2.4.1 eventually). But then I'm having troubles with `rake db:setup`. I don't have a solution for that error yet.

what's the error message that failed your ruby 2.3.1 installation?

**Comment by an-ju** [comment]
> > > > > > I had the problem with OpenSSL when setting it up locally. If this is a common problem, please refer to a good solution to it in your README.
> > > > > 
> > > > > 
> > > > > one of our team members had an openssl issue, but I forget how we resolved it
> > > > 
> > > > 
> > > > OK... There're still problems with setting the app up. Please create a Tracker story to record the problem. Please update the README and let me know when the updates are done.
> > > 
> > > 
> > > wait, what exactly are the problems?
> > 
> > 
> > I changed my ruby version to a version that has OpenSSL (2.4.1 eventually). But then I'm having troubles with `rake db:setup`. I don't have a solution for that error yet.
> 
> what's the error message that failed your ruby 2.3.1 installation?

```
Could not load OpenSSL.
You must recompile Ruby with OpenSSL support or change the sources in your Gemfile from 'https' to 'http'. Instructions for compiling with OpenSSL using RVM are available at rvm.io/packages/openssl.
```
and changing Gemfile's source of rubygems didn't really help.

**Comment by Chenlibo** [comment]
> > > > > > > I had the problem with OpenSSL when setting it up locally. If this is a common problem, please refer to a good solution to it in your README.
> > > > > > 
> > > > > > 
> > > > > > one of our team members had an openssl issue, but I forget how we resolved it
> > > > > 
> > > > > 
> > > > > OK... There're still problems with setting the app up. Please create a Tracker story to record the problem. Please update the README and let me know when the updates are done.
> > > > 
> > > > 
> > > > wait, what exactly are the problems?
> > > 
> > > 
> > > I changed my ruby version to a version that has OpenSSL (2.4.1 eventually). But then I'm having troubles with `rake db:setup`. I don't have a solution for that error yet.
> > 
> > 
> > what's the error message that failed your ruby 2.3.1 installation?
> 
> ```
> Could not load OpenSSL.
> You must recompile Ruby with OpenSSL support or change the sources in your Gemfile from 'https' to 'http'. Instructions for compiling with OpenSSL using RVM are available at rvm.io/packages/openssl.
> ```
> 
> and changing Gemfile's source of rubygems didn't really help.

Could you try to first `brew install openssl` if you don't have it and include `--with-openssl-dir='brew --prefix openssl'` when you install 2.3.1

**Comment by Chenlibo** [comment]
> > > > > > > > I had the problem with OpenSSL when setting it up locally. If this is a common problem, please refer to a good solution to it in your README.
> > > > > > > 
> > > > > > > 
> > > > > > > one of our team members had an openssl issue, but I forget how we resolved it
> > > > > > 
> > > > > > 
> > > > > > OK... There're still problems with setting the app up. Please create a Tracker story to record the problem. Please update the README and let me know when the updates are done.
> > > > > 
> > > > > 
> > > > > wait, what exactly are the problems?
> > > > 
> > > > 
> > > > I changed my ruby version to a version that has OpenSSL (2.4.1 eventually). But then I'm having troubles with `rake db:setup`. I don't have a solution for that error yet.
> > > 
> > > 
> > > what's the error message that failed your ruby 2.3.1 installation?
> > 
> > 
> > ```
> > Could not load OpenSSL.
> > You must recompile Ruby with OpenSSL support or change the sources in your Gemfile from 'https' to 'http'. Instructions for compiling with OpenSSL using RVM are available at rvm.io/packages/openssl.
> > ```
> > 
> > 
> > and changing Gemfile's source of rubygems didn't really help.
> 
> Could you try to first `brew install openssl` if you don't have it then include `--with-openssl-dir='brew --prefix openssl'` when you install 2.3.1?

**Comment by Chenlibo** [comment]
> > > > > > > > > I had the problem with OpenSSL when setting it up locally. If this is a common problem, please refer to a good solution to it in your README.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > one of our team members had an openssl issue, but I forget how we resolved it
> > > > > > > 
> > > > > > > 
> > > > > > > OK... There're still problems with setting the app up. Please create a Tracker story to record the problem. Please update the README and let me know when the updates are done.
> > > > > > 
> > > > > > 
> > > > > > wait, what exactly are the problems?
> > > > > 
> > > > > 
> > > > > I changed my ruby version to a version that has OpenSSL (2.4.1 eventually). But then I'm having troubles with `rake db:setup`. I don't have a solution for that error yet.
> > > > 
> > > > 
> > > > what's the error message that failed your ruby 2.3.1 installation?
> > > 
> > > 
> > > ```
> > > Could not load OpenSSL.
> > > You must recompile Ruby with OpenSSL support or change the sources in your Gemfile from 'https' to 'http'. Instructions for compiling with OpenSSL using RVM are available at rvm.io/packages/openssl.
> > > ```
> > > 
> > > 
> > > and changing Gemfile's source of rubygems didn't really help.
> > 
> > 
> > Could you try to first `brew install openssl` if you don't have it then include `--with-openssl-dir='brew --prefix openssl'` when you install 2.3.1?
I believe this is how I resolved the issue last time I encountered

**Comment by Chenlibo** [comment]
> > > > > > > I had the problem with OpenSSL when setting it up locally. If this is a common problem, please refer to a good solution to it in your README.
> > > > > > 
> > > > > > 
> > > > > > one of our team members had an openssl issue, but I forget how we resolved it
> > > > > 
> > > > > 
> > > > > OK... There're still problems with setting the app up. Please create a Tracker story to record the problem. Please update the README and let me know when the updates are done.
> > > > 
> > > > 
> > > > wait, what exactly are the problems?
> > > 
> > > 
> > > I changed my ruby version to a version that has OpenSSL (2.4.1 eventually). But then I'm having troubles with `rake db:setup`. I don't have a solution for that error yet.
> > 
> > 
> > what's the error message that failed your ruby 2.3.1 installation?
> 
> ```
> Could not load OpenSSL.
> You must recompile Ruby with OpenSSL support or change the sources in your Gemfile from 'https' to 'http'. Instructions for compiling with OpenSSL using RVM are available at rvm.io/packages/openssl.
> ```
> 
> and changing Gemfile's source of rubygems didn't really help.

Could you try to first `brew install openssl` if you don't have it then include `--with-openssl-dir='brew --prefix openssl'` when you install 2.3.1?

I believe this is how I resolved the issue last time I encountered

**Comment by an-ju** [comment]
> > > > > > > > I had the problem with OpenSSL when setting it up locally. If this is a common problem, please refer to a good solution to it in your README.
> > > > > > > 
> > > > > > > 
> > > > > > > one of our team members had an openssl issue, but I forget how we resolved it
> > > > > > 
> > > > > > 
> > > > > > OK... There're still problems with setting the app up. Please create a Tracker story to record the problem. Please update the README and let me know when the updates are done.
> > > > > 
> > > > > 
> > > > > wait, what exactly are the problems?
> > > > 
> > > > 
> > > > I changed my ruby version to a version that has OpenSSL (2.4.1 eventually). But then I'm having troubles with `rake db:setup`. I don't have a solution for that error yet.
> > > 
> > > 
> > > what's the error message that failed your ruby 2.3.1 installation?
> > 
> > 
> > ```
> > Could not load OpenSSL.
> > You must recompile Ruby with OpenSSL support or change the sources in your Gemfile from 'https' to 'http'. Instructions for compiling with OpenSSL using RVM are available at rvm.io/packages/openssl.
> > ```
> > 
> > 
> > and changing Gemfile's source of rubygems didn't really help.
> 
> Could you try to first `brew install openssl` (assuming you are using a mac) if you don't have it then include `--with-openssl-dir='brew --prefix openssl'` when you install 2.3.1?
> 
> I believe this is how I resolved the issue last time I encountered

OK.  The second solution in [this post](https://stackoverflow.com/questions/15511943/troubles-with-rvm-and-openssl) solved the problem.  It's similar to the one you proposed but using rvm's package instead.

**Comment by an-ju** [comment]
Others look good.  However, when running cucumber, I have this error

```
    And I select "Berkeley Student Cooperative" from "Organization"                        # features/step_definitions/web_steps.rb:85
      Element <option> could not be scrolled into view (Selenium::WebDriver::Error::ElementNotInteractableError)
      WebDriverError@chrome://marionette/content/error.js:179:5
      ElementNotInteractableError@chrome://marionette/content/error.js:287:5
      webdriverClickElement@chrome://marionette/content/interaction.js:160:11
      interaction.clickElement@chrome://marionette/content/interaction.js:131:11
      clickElement/<@chrome://marionette/content/listener.js:1211:14
      navigate/<@chrome://marionette/content/listener.js:411:13
      navigate@chrome://marionette/content/listener.js:410:13
      clickElement@chrome://marionette/content/listener.js:1210:5
      ./features/step_definitions/web_steps.rb:86:in `/^(?:|I )select "([^"]*)" from "([^"]*)"$/'
      features/clear_form.feature:49:in `And I select "Berkeley Student Cooperative" from "Organization"'
```

I discussed this problem in my OH.  Can you remind me of the solution/result of that discussion?

**Comment by Chenlibo** [comment]
> Others look good. However, when running cucumber, I have this error
> 
> ```
>     And I select "Berkeley Student Cooperative" from "Organization"                        # features/step_definitions/web_steps.rb:85
>       Element <option> could not be scrolled into view (Selenium::WebDriver::Error::ElementNotInteractableError)
>       WebDriverError@chrome://marionette/content/error.js:179:5
>       ElementNotInteractableError@chrome://marionette/content/error.js:287:5
>       webdriverClickElement@chrome://marionette/content/interaction.js:160:11
>       interaction.clickElement@chrome://marionette/content/interaction.js:131:11
>       clickElement/<@chrome://marionette/content/listener.js:1211:14
>       navigate/<@chrome://marionette/content/listener.js:411:13
>       navigate@chrome://marionette/content/listener.js:410:13
>       clickElement@chrome://marionette/content/listener.js:1210:5
>       ./features/step_definitions/web_steps.rb:86:in `/^(?:|I )select "([^"]*)" from "([^"]*)"$/'
>       features/clear_form.feature:49:in `And I select "Berkeley Student Cooperative" from "Organization"'
> ```
> 
> I discussed this problem in my OH. Can you remind me of the solution/result of that discussion?

We didn't modify the test code. Instead, we changed the Travis ci config file so that all tests can be passed. You can check the details in `.travis.yml`. Essentially a hack.

**Comment by Chenlibo** [comment]
> Please update the README about the new features.

added

**Comment by an-ju** [comment]
@armandofox Could you please merge this PR?

**Pull request merged**
