### PR TITLE
Merging the student code back to saasbook

### PR DESCRIPTION
**Pull request by andrewhalle**

### CODE REVIEW

**Comment by armandofox** [comment]
just making sure you have reviewed the PR changes and you are ok with them becomign "golden" before i hit merge....

Armando Fox
Professor, Computer Science Division
Faculty Advisor, UC Berkeley MOOCLab
581 Soda Hall MC#1776, Berkeley, CA 94720-1776
+1.510.642.6820 / http://www.cs.berkeley.edu/~fox <http://www.cs.berkeley.edu/~fox>

Learn to build software free at saas-class.org

**Comment by andrewhalle** [comment]
Yes I've tried their changes locally, and I think the student team did some
really good work, should be "golden". I made a few minor edits, and changed
their migrations to get rid of remove_column calls on tables that existed
before they started work, just to protect the database on
esaas-engagements. I'll also clone the database before I do the merge.
Other than that, looks good to me

**Comment by armandofox** [comment]
ok, so it's fine for me to merge the PR? just making sure given your comments about the db

Armando Fox
Professor, Computer Science Division
Faculty Advisor, UC Berkeley MOOCLab
581 Soda Hall MC#1776, Berkeley, CA 94720-1776
+1.510.642.6820 / http://www.cs.berkeley.edu/~fox <http://www.cs.berkeley.edu/~fox>

Learn to build software free at saas-class.org

**Comment by andrewhalle** [comment]
Yes I think it’s good to merge, just being cautious.

**Pull request merged**
